import { MetadataRoute } from "next";

export default function robots(): MetadataRoute.Robots {
  const baseUrl = "https://porraza.com";

  return {
    rules: [
      {
        userAgent: "*",
        allow: ["/", "/en/"],
        disallow: [
          "/dashboard",
          "/dashboard/*",
          "/predictions",
          "/predictions/*",
          "/schedule",
          "/schedule/*",
          "/leagues",
          "/leagues/*",
          "/leaderboard",
          "/leaderboard/*",
          "/stadiums",
          "/stadiums/*",
          "/teams",
          "/teams/*",
          "/rules",
          "/rules/*",
          "/settings",
          "/settings/*",
          "/checkout",
          "/checkout/*",
          "/login",
          "/signup",
          "/verify-email",
          "/reset-password",
          "/en/dashboard",
          "/en/dashboard/*",
          "/en/predictions",
          "/en/predictions/*",
          "/en/schedule",
          "/en/schedule/*",
          "/en/leagues",
          "/en/leagues/*",
          "/en/leaderboard",
          "/en/leaderboard/*",
          "/en/stadiums",
          "/en/stadiums/*",
          "/en/teams",
          "/en/teams/*",
          "/en/rules",
          "/en/rules/*",
          "/en/settings",
          "/en/settings/*",
          "/en/checkout",
          "/en/checkout/*",
          "/en/login",
          "/en/signup",
          "/en/verify-email",
          "/en/reset-password",
        ],
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
  };
}
